### PR TITLE
[snap/frontend]: Added fee multiplier component.

### PR DESCRIPTION
**Pull request by AnthonyLaw**
## What was the issue?
- The fee multiplier option is missing in the transfer form.

## What's the fix?
- Query fee multiplier from snap state.
- Added fee multiplier frontend.

## Preview
image

### CODE REVIEW

**Review by Wayonb — CHANGES_REQUESTED** [review]
Looks good, but a couple of questions
1. how does the user know what fee values are slow, average, and fast?
2. Can the user set a custom fee?

**Comment by AnthonyLaw** [comment]
> Looks good, but a couple of questions
> 
> 1. how does the user know what fee values are slow, average, and fast?
> 2. Can the user set a custom fee?

1. I was thinking of implementing fees (tx size * fee multiplier) in this screen, which means I must create and prepare transactions in the front end, which doesn't look good (because I want it to implement prepare transactions in the backend)

- does it make sense we just showing fee multiplier and the fees will be displayed in the last confirmation screen?
image


2. Nope, but I can add it in the future.

**Comment by Wayonb** [comment]
> > Looks good, but a couple of questions
> > 
> > 1. how does the user know what fee values are slow, average, and fast?
> > 2. Can the user set a custom fee?
> 
> 1. I was thinking of implementing fees (tx size * fee multiplier) in this screen, which means I must create and prepare transactions in the front end, which doesn't look good (because I want it to implement prepare transactions in the backend)
> 
> * does it make sense we just showing fee multiplier and the fees will be displayed in the last confirmation screen?
> 
> image
> 2. Nope, but I can add it in the future.
1. yea, that might work but I would verify with @0x6861746366574 
   tbh, not sure if these are needed since most tx will get committed in the next block

**Review by Wayonb — APPROVED** [review]
👍🏾

**Review by Wayonb — APPROVED** [review]
👍🏾

**Pull request merged**
